apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-sdk-service-account
  namespace: roboshop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::854481201869:role/aws-secret-role
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sdk-deployment
  namespace: roboshop
  labels:
    app: aws-sdk-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: aws-sdk-app

  template:
    metadata:
      labels:
        app: aws-sdk-app

    spec:
      serviceAccountName: aws-sdk-service-account

      containers:
      - name: aws-sdk-container
        image: 854481201869.dkr.ecr.us-east-1.amazonaws.com/awssdk/secrets:v2
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: AWS_REGION
          value: us-east-1

        - name: SECRET_NAME
          value: roboshop/dev/mysql_password

---
apiVersion: v1
kind: Service
metadata:
  name: aws-sdk-service
  namespace: roboshop

spec:
  selector:
    app: aws-sdk-app

  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

  type: ClusterIP